# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_satellite.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setStyleSheet(_fromUtf8("background-image: url(:/images/earth.png);"))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_11 = QtGui.QPushButton(self.frame)
        self.pushButton_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_3.addWidget(self.pushButton_11, 6, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 5, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.frame)
        self.pushButton_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 3, 2, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        self.pushButton_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_3.addWidget(self.pushButton_12, 7, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 4, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TeX Gyre Pagella"))
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.frame)
        self.pushButton_13.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_3.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.frame)
        self.pushButton_14.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_3.addWidget(self.pushButton_14, 2, 3, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.frame)
        self.pushButton_15.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_3.addWidget(self.pushButton_15, 3, 3, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        self.pushButton_16.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_3.addWidget(self.pushButton_16, 4, 3, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 5, 3, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.frame)
        self.pushButton_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 6, 3, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 4, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 2, 4, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_3.addWidget(self.pushButton_10, 3, 4, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_3.addWidget(self.pushButton_17, 4, 4, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_3.addWidget(self.pushButton_18, 5, 4, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_3.addWidget(self.pushButton_19, 1, 5, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_3.addWidget(self.pushButton_20, 2, 5, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_3.addWidget(self.pushButton_21, 3, 5, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_3.addWidget(self.pushButton_22, 4, 5, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 2, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 2, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_13, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_15, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_16, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_17, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_18, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_19, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_21, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_22, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "卫星状态", None))
        self.label_6.setText(_translate("MainWindow", "2018-09-26　08：26：23　时间有效", None))
        self.label_5.setText(_translate("MainWindow", "卫星状态", None))
        self.pushButton_11.setText(_translate("MainWindow", "卫星 5", None))
        self.pushButton_2.setText(_translate("MainWindow", "卫星 4", None))
        self.pushButton_5.setText(_translate("MainWindow", "卫星 2", None))
        self.pushButton_12.setText(_translate("MainWindow", "卫星 6", None))
        self.pushButton_4.setText(_translate("MainWindow", "卫星 3", None))
        self.pushButton.setText(_translate("MainWindow", "卫星 0", None))
        self.pushButton_3.setText(_translate("MainWindow", "卫星 1", None))
        self.pushButton_13.setText(_translate("MainWindow", "卫星 7", None))
        self.pushButton_14.setText(_translate("MainWindow", "卫星 8", None))
        self.pushButton_15.setText(_translate("MainWindow", "卫星 9", None))
        self.pushButton_16.setText(_translate("MainWindow", "卫星 10", None))
        self.pushButton_6.setText(_translate("MainWindow", "卫星 11", None))
        self.pushButton_7.setText(_translate("MainWindow", "卫星 12", None))
        self.pushButton_8.setText(_translate("MainWindow", "卫星 13", None))
        self.pushButton_9.setText(_translate("MainWindow", "卫星 14", None))
        self.pushButton_10.setText(_translate("MainWindow", "卫星 15", None))
        self.pushButton_17.setText(_translate("MainWindow", "卫星 16", None))
        self.pushButton_18.setText(_translate("MainWindow", "卫星 17", None))
        self.pushButton_19.setText(_translate("MainWindow", "卫星 18", None))
        self.pushButton_20.setText(_translate("MainWindow", "卫星 19", None))
        self.pushButton_21.setText(_translate("MainWindow", "卫星 20", None))
        self.pushButton_22.setText(_translate("MainWindow", "卫星 21", None))

    def show_image(self):
        source = QtCore.QObject.sender(self.centralwidget)
        dir_name = source.text().split(' ')[-1]
        file_path = 'data/' + dir_name + '/'
        # print(file_path)
        pixmap1 = QtGui.QPixmap(file_path + "AZ-1.png")
        pixmap1 = pixmap1.scaled(self.label.width(), self.label.height())
        self.label.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "CN-1.png")
        pixmap1 = pixmap1.scaled(self.label_2.width(), self.label_2.height())
        self.label_2.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "EL-1.png")
        pixmap1 = pixmap1.scaled(self.label_3.width(), self.label_3.height())
        self.label_3.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "PR-1.png")
        pixmap1 = pixmap1.scaled(self.label_4.width(), self.label_4.height())
        self.label_4.setPixmap((pixmap1))

import resources_rc

app = QtGui.QApplication([])
wget = QtGui.QMainWindow()
form = Ui_MainWindow()
form.setupUi(wget)
wget.show()
# exm = Ui_Form()
# form.show()
app.exec_()
