# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_satellite.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 4, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 2, 3, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_3.addWidget(self.pushButton_15, 9, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 3, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_3.addWidget(self.pushButton_10, 4, 3, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_3.addWidget(self.pushButton_14, 8, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 3, 3, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_3.addWidget(self.pushButton_12, 6, 2, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_3.addWidget(self.pushButton_11, 5, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_3.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_3.addWidget(self.pushButton_13, 7, 2, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_3.addWidget(self.pushButton_16, 10, 2, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_3.addWidget(self.pushButton_17, 5, 3, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_3.addWidget(self.pushButton_18, 6, 3, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_3.addWidget(self.pushButton_19, 7, 3, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_3.addWidget(self.pushButton_20, 8, 3, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_3.addWidget(self.pushButton_21, 9, 3, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_3.addWidget(self.pushButton_22, 10, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 2, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_11, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_12, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_13, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_15, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_16, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_17, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_18, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_19, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_21, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)
        QtCore.QObject.connect(self.pushButton_22, QtCore.SIGNAL(_fromUtf8("clicked()")), self.show_image)

        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow", None))
        self.label_2.setText(_translate("mainWindow", "", None))
        self.label_4.setText(_translate("mainWindow", "", None))
        self.label_3.setText(_translate("mainWindow", "", None))
        self.label.setText(_translate("mainWindow", "", None))
        self.pushButton_2.setText(_translate("mainWindow", "Satellite 4", None))
        self.pushButton_8.setText(_translate("mainWindow", "Satellite 13", None))
        self.pushButton_15.setText(_translate("mainWindow", "Satellite 9", None))
        self.pushButton_6.setText(_translate("mainWindow", "Satellite 11", None))
        self.pushButton_3.setText(_translate("mainWindow", "Satellite 1", None))
        self.pushButton.setText(_translate("mainWindow", "Satellite 0", None))
        self.pushButton_7.setText(_translate("mainWindow", "Satellite 12", None))
        self.pushButton_10.setText(_translate("mainWindow", "Satellite 15", None))
        self.pushButton_14.setText(_translate("mainWindow", "Satellite 8", None))
        self.pushButton_9.setText(_translate("mainWindow", "Satellite 14", None))
        self.pushButton_12.setText(_translate("mainWindow", "Satellite 6", None))
        self.pushButton_11.setText(_translate("mainWindow", "Satellite 5", None))
        self.pushButton_5.setText(_translate("mainWindow", "Satellite 2", None))
        self.pushButton_4.setText(_translate("mainWindow", "Satellite 3", None))
        self.pushButton_13.setText(_translate("mainWindow", "Satellite 7", None))
        self.pushButton_16.setText(_translate("mainWindow", "Satellite 10", None))
        self.pushButton_17.setText(_translate("mainWindow", "Satellite 16", None))
        self.pushButton_18.setText(_translate("mainWindow", "Satellite 17", None))
        self.pushButton_19.setText(_translate("mainWindow", "Satellite 18", None))
        self.pushButton_20.setText(_translate("mainWindow", "Satellite 19", None))
        self.pushButton_21.setText(_translate("mainWindow", "Satellite 20", None))
        self.pushButton_22.setText(_translate("mainWindow", "Satellite 21", None))

    def show_image(self):
        source = QtCore.QObject.sender(self.centralwidget)
        dir_name = source.text().split(' ')[-1]
        file_path = '../images/' + dir_name + '/'
        print(file_path)
        pixmap1 = QtGui.QPixmap(file_path + "AZ-1.png")
        pixmap1 = pixmap1.scaled(self.label.width(), self.label.height())
        self.label.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "CN-1.png")
        pixmap1 = pixmap1.scaled(self.label_2.width(), self.label_2.height())
        self.label_2.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "EL-1.png")
        pixmap1 = pixmap1.scaled(self.label_3.width(), self.label_3.height())
        self.label_3.setPixmap((pixmap1))
        pixmap1 = QtGui.QPixmap(file_path + "PR-1.png")
        pixmap1 = pixmap1.scaled(self.label_4.width(), self.label_4.height())
        self.label_4.setPixmap((pixmap1))

app = QtGui.QApplication([])
wget = QtGui.QMainWindow()
form = Ui_mainWindow()
form.setupUi(wget)
wget.show()
# exm = Ui_Form()
# form.show()
app.exec_()